// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGkA4GHYLWpYZ64YRJkhZEmPsxMWQYaqo',
    appId: '1:1011819283860:web:8549a35bbfa7a89bf27b81',
    messagingSenderId: '1011819283860',
    projectId: 'advexam-65856',
    authDomain: 'advexam-65856.firebaseapp.com',
    storageBucket: 'advexam-65856.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3KlZRlSp9J744al2VQ8HYoSUjahDyX3E',
    appId: '1:1011819283860:android:900af19093d3c7aef27b81',
    messagingSenderId: '1011819283860',
    projectId: 'advexam-65856',
    storageBucket: 'advexam-65856.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMmsDB_xzGL6HsbFhDbTiE-51zYVdyggk',
    appId: '1:1011819283860:ios:4031c5ab2d307379f27b81',
    messagingSenderId: '1011819283860',
    projectId: 'advexam-65856',
    storageBucket: 'advexam-65856.appspot.com',
    iosBundleId: 'com.example.advExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMmsDB_xzGL6HsbFhDbTiE-51zYVdyggk',
    appId: '1:1011819283860:ios:4031c5ab2d307379f27b81',
    messagingSenderId: '1011819283860',
    projectId: 'advexam-65856',
    storageBucket: 'advexam-65856.appspot.com',
    iosBundleId: 'com.example.advExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGkA4GHYLWpYZ64YRJkhZEmPsxMWQYaqo',
    appId: '1:1011819283860:web:d24762476610d079f27b81',
    messagingSenderId: '1011819283860',
    projectId: 'advexam-65856',
    authDomain: 'advexam-65856.firebaseapp.com',
    storageBucket: 'advexam-65856.appspot.com',
  );
}
